### ISSUE TITLE
Add Versioning for documentation by repository.

### ISSUE THREAD

**Issue by srinjoyc** [onflow/developer-portal#195]
DoD
- [ ] Contributors can provide a `release-tag` to show by default (they should be able to define this). Other versions should be able to be accessed.

**Comment by schpet** [comment]
FYI the mock developer docs repo now has versioned docs, next up would be for the next-docs-v1 to support reading and using this info 

- https://github.com/onflow/mock-developer-doc/pull/2

note the new `versioned_docs` directory here:

https://github.com/onflow/mock-developer-doc/tree/e4df424e83a5fd5b6c97c3f4f903a6fc4149ef72

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs
