### ISSUE TITLE
Add Monitoring and Logging Tooling

### ISSUE THREAD

**Issue by srinjoyc** [onflow/developer-portal#196]
DoD
- [x] We can measure errors produced by FE (sentry)
- [ ] Alerts for Sentry
- [ ] Redis cluster can be debugged and has alerts to slack
- [ ] Measure other things: MixPanel events

**Comment by gpavlov2016** [comment]
- Redis cluster @sjonpaulbrown (SRE team)
- Add logging when refresh endpoint is being called @10thfloor 
- Check deployment provider fly.io for error code stats @10thfloor 
- Mixpanel needs to track active users over time, not critical can be implemented later

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs
