### ISSUE TITLE
[Jul 8 Launch] UI Issues

### ISSUE THREAD

**Issue by srinjoyc** [onflow/developer-portal#415]
# Major 

- [x] 🚨 Image & video issues [Jul 8 Launch] @10thfloor 
-  Images and videos are still missing (ie. /learn/kitty-items).
-  office hours logo is missing (resolved by #418)

- [x] 🚨 URLs [Jul 8 Launch] (@aureentuluvacal)
- When a URL ends with `/` ie. `/flow/dapp-development/flow-dapp-anatomy/` vs `/flow/dapp-development/flow-dapp-anatomy` - the first one breaks the page. This may be common while sharing and referencing links so it shouldn't break the page.

- [x] #432
- Really needed specifically for this case: `https://flow-docs-staging.fly.dev/flow/dapp-development` - in order for the user to see there are other pages here, they need to click on 'next'.

- [x] 🚨 Move the following into`/tools/xxx` route: [Jul 8 Launch] (@codingone21)
Issue Created: https://github.com/onflow/next-docs-v1/issues/417
- fcl-js
- flow-js-testing
- flow-go-sdk
- flow-cli
- emulator
- Please also search and replace the links to match this new routing

- Move `/learn/nft-marketplace` to `/flow/nft-marketplace` 
  - Include in 'Flow' section in left sidebar

- [x] 🚨  Repo Switcher Contents: [Jul 8 Launch] (@joekrill)
```
Tools
- CLI
- FCL
- Go SDK
- HTTP API
- Emulator
- VS Code Extension
- All tools (goes to /tools) 

Learn
- Cadence
- Kitty Items
- Concepts & Guides (goes to /flow)
- All content (goes to /learn)

Nodes
- Operation
- Staking
- Flow Port
- All nodes (goes to /nodes)
```

# Minor
- [x] Page Routing to subsections ⚠️ [Jul 8 Launch]: (@neilZon - 2)
  - A url like `https://flow-docs-staging.fly.dev/tools#sdks` should go directly to the SDK section. Currently it does not scroll down to the section as it should.

- [x] Secondary navigation on landing pages (@aureentuluvacal)
  - Maybe use the purple text as the selected section over the current box - similar to the navigation of internal pages. 
 
 - [x] On main nav ⚠️ [Jul 8 Launch]: (@10thfloor )
   - Show external links with the upward arrow to indicate that.
   - Main nav should close once a link is clicked. 

- [x] Images ⚠️ [Jul 8 Launch]: (@neilZon - 3) - @aureentuluvacal 
  - office hours logo is missing

- [x] Internal pages ⚠️ [Jul 8 Launch]: (@neilZon - 1)
  - increase margin/padding between the bottom of the internal page and footer. Roughly should be 25-50% of the footer height - use your best judgment here.
  - The current page should always be highlighted on the left side of the menu. Currently when going to an index page of a section.
  - When you click on a link in an internal page, you should go to the top of the page vs currently you stay in the same scroll position. Reset to top.

**Comment by srinjoyc** [comment]
Mack
- front matter not working - for cadence and fcl docs
- review hannah's pr for content structure 
- fixes to headers 
- trailing slash thing
- images + video not loading
-

**Comment by neilZon** [comment]
update: 
 Internal pages ⚠️ [Jul 8 Launch]: (@neilZon - 1)

> - [x] increase margin/padding between the bottom of the internal page and footer. Roughly should be 25-50% of the footer height - use your best judgment here.
> - [x] The current page should always be highlighted on the left side of the menu. Currently when going to an index page of a section.
> - [ ] When you click on a link in an internal page, you should go to the top of the page vs currently you stay in the same scroll position. Reset to top.

First 2 fixes are done and in PR. Struggling with last one but @aureentuluvacal offered to take it up so the fixes are going to be in separate PRs.

**Comment by neilZon** [comment]
>  - [ ] Page Routing to subsections ⚠️ [Jul 8 Launch]: (@neilZon - 2)
> 
> * A url like https://flow-docs-staging.fly.dev/tools#sdks should go directly to the SDK section. Currently it does not scroll down to the section as it should.

@srinjoyc I'm not able to reproduce this on the tools page. Is there any other page that has this issue?
