### ISSUE TITLE
Search Results Improvment

### ISSUE THREAD

**Issue by codingone21** [onflow/developer-portal#462]
We should try to get to add more to matched results with the Algolia Search

**Comment by alxflw** [comment]
As discussed last Friday, this should:
- improve search results 
- not open search results in a new tab
- be inspired by Algolia's search UI 
- maybe: generate search URLs (eg https://www.algolia.com/doc/?q=analytics) ?

It is marked as a nice to have for the release, so should come after high prio items

**Comment by codingone21** [comment]
Tracking Changes

- [ ] Added ordering of importance per search attributes: Title -> Description -> Headers -> Content

- [ ] Fixed the overlapping indexes between staging/prod search indexes
- [ ] Remove duplicate paths like this: anyPath & anyPath/
- [ ] Create a better 'title' from url path. Right now, it defaults to "Welcome to the Flow Developer Portal" or "Section Name | Flow Developer Portal" or "Flow Developer Portal". This involves frontmatter and social metas, should be a separate ticket & workflow.

**Comment by 10thfloor** [comment]
This issue no longer needs to cover: 

> `Remove duplicate paths with trailing slashes like this: anyPath & anyPath/`

Since that will be handeled by the changes going into https://github.com/onflow/next-docs-v1/issues/487
can we close this? 

What remains to be done for: 

> Create a better 'title' from url path. Right now, it defaults to "Welcome to the Flow Developer Portal" or "Section Name | Flow Developer Portal" or "Flow Developer Portal". This involves frontmatter and social metas, should be a separate ticket & workflow.

?

**Comment by codingone21** [comment]
> #487

I'm not sure the #487 handled all the trailing slashes with duplicate entries, since I still see the indexes in Algolia (example below with 'flow-js-testing').
<img width="1507" alt="Screen Shot 2022-08-15 at 1 40 12 PM" src="https://user-images.githubusercontent.com/18616121/184686902-74752b27-33ca-40c1-a681-6b54eef1b21c.png">
<img width="719" alt="Screen Shot 2022-08-15 at 1 40 50 PM" src="https://user-images.githubusercontent.com/18616121/184687065-42a5961e-0f28-4189-a463-f251edeeba47.png">
.

I think it's easier to keep this issue open, but I can also close this and create separate issues for the frontmatter title and trailing slashes indexes if that's preferred!

**Comment by codingone21** [comment]
The duplicates (trailing slashes) were updated correctly after I restarted crawler and refreshed the indexes!

**Comment by 10thfloor** [comment]
@srinjoyc @codingone21  What remains to be done here? Can we close this?
