### ISSUE TITLE
NFT Storefront v2 doc updates: contracts and examples

### ISSUE THREAD

**Issue by alxflw** [onflow/developer-portal#469]
We need to revisit this section in the portal: https://developers.onflow.org/flow/core-contracts.

We need to add the NFT Storefront, Royalty view and switchboard. Also we should audit any other missing ones to the list.

For each, we need to:
- Create content 
- Add to new markdown file
- Add new file to the navigation

**Comment by franklywatson** [comment]
This will be the content structure for when the docs are published

- High level overview
    - Primer on why you have storefront in your account
    - High level focus on use cases that matter to the reader, help them focus on basic vs advanced
    - Reference to use cases that can be supported
        - eg: how to list on a given marketplace
        - Existing shared marketplaces that support you using NFT Storefront
- Technical specifications
    - Functional definitions (contract addresses, APIs/methods, events emitted etc)
    - Transactions
        - Setup the storefront
        - Listing NFT for sale
        - NFT sale
        - Deleting a listing
        - Changing price on a listing
        - Cleanup expired listing
    - Scripts
- [https://docs.onflow.org/nft-marketplace/selling-nfts/](https://docs.onflow.org/nft-marketplace/selling-nfts/)
    - Needs extending to reflect all the new V2 things
- Contract integration examples
    - Use cases
        - Peer-to-peer sales (eg: marketplaces)
        - Basic vs advanced integration
    - User stories
        - Sell your NFT, no royalties and no support for multiple token types
            - NFT Storefront V2
        - Sell your NFT with support for multiple token types when sold
            - NFT Storefront V2 + Switchboard
        - Sell your NFT with royalties support specific to marketplaces
            - NFT Storefront V2 + Royalties View
- Tutorial

- Migration guide for existing V1 users
    - [Tech Spec - NFTStorefrontV2](https://www.notion.so/Tech-Spec-NFTStorefrontV2-753283f9746b428c901b3099710cf84e)
    - Examples for people needing to upgrade
