### ISSUE TITLE
Mobile Performance Issues

### ISSUE THREAD

**Issue by srinjoyc** [onflow/developer-portal#572]
There are some optimizations we can do to improve the mobile performance - this will help get better SEO for the docs site as well as enable a better mobile experience.

Let's address top quick wins from here, and aim for a score above 80. 

https://pagespeed.web.dev/report?url=https%3A%2F%2Fdevelopers.flow.com%2F&form_factor=mobile

**Comment by nialexsan** [comment]
https://github.com/onflow/docs/issues/257
