### ISSUE TITLE
Create Cadence best practices page

### ISSUE THREAD

**Issue by j1010001** [onflow/developer-portal#583]
When Halborn finished security audit for Secure Cadence, they also published list of security practices for Flow smart contract devs: https://halborn.com/best-security-practices-for-cadence-developers-flow/ 

We should add this to our Cadence docs (we can copy the content and just have a link to the original blog post at the bottom to give credit to Halborn) - confirmation from Halborn attached.

**Comment by j1010001** [comment]
<img width="578" alt="Screen Shot 2022-08-16 at 3 19 48 PM" src="https://user-images.githubusercontent.com/24554599/184995214-5fa40f2a-96ba-4406-9900-bb935155d639.png">

**Comment by 10thfloor** [comment]
@j1010001 You can add this docuemnt to the cadence repo in the `docs` folder. 
Once it is there it will be available on the docs site. 
lmk when you add it, and We can add a menu entry for this.

**Comment by j1010001** [comment]
Hi @10thfloor - turns out this was already done by #[1063](https://github.com/onflow/flow/issues/1063) (https://developers.flow.com/cadence/security-best-practices), but I don't think we have a menu item for it. I think this should be in the side menu.

**Comment by 10thfloor** [comment]
Ok leave it to me, I'll add the menu link.

**Comment by 10thfloor** [comment]
cc @turbolent Now you know how to create menu links, would you like to try closing this one?

**Comment by j1010001** [comment]
Menu link is added, closing
