### ISSUE TITLE
FCL JS API Table of Contents links -> 404

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/developer-portal#601]
Links from [FCL JS API ](https://developers.flow.com/tools/fcl-js/reference/api) table of contents lead to 404. 

It appears that hash links are prepended with `/tools/fcl-js/reference` while they should be prepended with  `/tools/fcl-js/reference/api` to lead to the correct url

**Comment by chasefleming** [comment]
Anchor links in right column aren't working
