### ISSUE TITLE
Migrate existing repos to `flow-docs.json`

### ISSUE THREAD

**Issue by 10thfloor** [onflow/developer-portal#616]
We'll need to update each repo with a `flow-docs.json` (the file containing the menu definition and other user-defined metadata).

- [ ] Remove `call-refresh-doc.yml` from all repos. 

Add `flow-docs.json` to the following repos:
- [x] fcl
- [ ] emulator
- [ ] cli
- [ ] go sdk
- [ ] js sdk
- [ ] flow-cadut
- [ ] js-testing
- [ ] kitty-items
- [ ] onflow/flow* This one might require some thought as there are _multiple_ side-menus for this content
- [x] cadence 
- [ ] sdks
- [ ] etc ... ?

**Comment by schpet** [comment]
cadence:

- https://github.com/onflow/cadence/pull/1908
- https://github.com/onflow/cadence/pull/1909

**Comment by schpet** [comment]
fcl:

- https://github.com/onflow/fcl-js/pull/1378

**Comment by 10thfloor** [comment]
https://github.com/onflow/fcl-js/pull/1378/files

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs
