### ISSUE TITLE
Weird mouseover behaviour

### ISSUE THREAD

**Issue by 10thfloor** [onflow/developer-portal#618]
The video shows the behaviour. 
This issue should also include fixing the icon color in dark mode. 

https://user-images.githubusercontent.com/901466/186724906-9df6d83e-956e-4d75-b2f3-361abadb54de.mov

**Comment by joekrill** [comment]
> This issue should also include fixing the icon color in dark mode.

What does this mean exactly? What is it supposed to look like? Is this the main icon? Or just or hover? Or both?

**Comment by 10thfloor** [comment]
The icon that is "</>" should be white in dark mode.
