### ISSUE TITLE
Run Algolia Crawler on Refresh 

### ISSUE THREAD

**Issue by 10thfloor** [onflow/developer-portal#652]
It is necessary to run the Algolia crawler when new documents are added to the site, so that they are available in search results immediately.

Part of this issue is adding reporting if there are errors.

- [ ] Re-index the site in Algolia when content changes using the Algolia REST API: https://www.algolia.com/doc/rest-api/crawler/

Suggested approach for error reporting: 
- [ ] Report any links that are crawled that result in 500 or 404 HTTP error. Errors generated by the repository submission that triggered the refresh webhook should be reported to that same repository in the for of an issue using the GitHub API.
- [ ] The "bad links" report should include information about _what page_ contains the links.

**Comment by nialexsan** [comment]
switched to typesense and static builds https://github.com/onflow/docs
