### ISSUE TITLE
Audit contributions for malformed links

### ISSUE THREAD

**Issue by 10thfloor** [onflow/developer-portal#662]
As part of the integrity of the portal site, we should continually monitor the health of links as dead links will effect thew overall user experience of the developer portal. 

Requirements: 
- Authors content should be scanned by code that is able to detect malformed or dead links. 
- Authors should receive feedback about bad links before their document is published

Prototype link checking code has already been implemented in earnest in the Cadence repo here: 
https://github.com/onflow/cadence/blob/master/docs/lint.js

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs
