### ISSUE TITLE
Ignore links with mailto hrefs

### ISSUE THREAD

**Issue by 10thfloor** [onflow/developer-portal#666]
**Describe the bug**
Currently our link parsing and reformatting code attemots to reformat `mailto` links. We can see this in Algolia: 
<img width="481" alt="Screen Shot 2022-09-23 at 12 47 02 PM" src="https://user-images.githubusercontent.com/901466/192046042-0ce809b1-fbc0-4df0-bf12-2a1dc277fe3a.png">

**Expected behavior**
Ignore / don't format links with `mailto` hrefs

**Comment by LaurenIke** [comment]
@joekrill do you need additional information to work on this bug?
