### ISSUE TITLE
Periodic scan to collect broken links on Developer Portal 

### ISSUE THREAD

**Issue by LaurenIke** [onflow/developer-portal#668]
## Feature Story
As a Dapper developer, I should be informed when a broken link is identified on the developer portal so that the team can troubleshoot and resolve the issue. 

## Technical Implementation Notes: 
- weekly Algolia crawler 
- bubble issues up to the team via Slack (developer working group slack channel) 

**Estimated Duration**
4 days

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs
