### ISSUE TITLE
“Double Render” regression

### ISSUE THREAD

**Issue by LaurenIke** [onflow/developer-portal#675]
## Issue: 
Users are seeing a double render on the site.  Developer is unable to reproduce this issue. 

Related prior reports and other docs:
https://www.notion.so/dapperlabs/Double-Render-regression-9c4294344aa848febe639d8f4fbc2a44
https://www.notion.so/dapperlabs/Double-Rendering-Bug-7acc49a1178a4fa99e53565aa48467d0
https://www.notion.so/dapperlabs/Dev-Portal-Bug-Fix-Summary-9ab38bed87464428a7d3b6c4727df7eb#7acc49a1178a4fa99e53565aa48467d0

**Comment by schpet** [comment]
related: https://github.com/onflow/developer-portal/issues/693

**Comment by schpet** [comment]
related: #560

**Comment by 10thfloor** [comment]
Got report From @alyssa-martin31 

**Browser**: Chrome Version 106.0.5249.119 (Official Build) (x86_64)

**Extensions Installed:** 
1Password – Password Manager
Application Launcher For Drive (by Google)
DetailsRemove
ColorZilla
GoFullPage - Full Page Screen Capture
Google Docs Offline
Lever Hire Extension
Okta Browser Plugin
Tab Save
TinEye Reverse Image Search
WhatFont
ZenHub for GitHub

How it Happenned: 
First Visit to the homepage in a month, by clicking link from `flow.com`

**Comment by 10thfloor** [comment]
Got Report from Dmitri F

**Browser:**

**Extensions Installed:**

**How it Happened:**

**Comment by 10thfloor** [comment]
It's still happening!

OSX Ventura
Chrome Version 109.0.5414.119 (Official Build) (arm64)

Followed this link: https://docs.onflow.org/fcl/reference/api
From here: https://github.com/onflow/developer-grants/issues/50

![Screenshot 2023-02-16 at 10 24 47 AM](https://user-images.githubusercontent.com/901466/219454720-9ea073cd-ad44-4822-8ce3-8b5e8da685cb.png)

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs
