### ISSUE TITLE
[SEO] Title tag and description excel

### ISSUE THREAD

**Issue by LaurenIke** [onflow/developer-portal#678]
Next action: 
- continue to follow up with Conway to get this excel document 
- this will unblock this ticket - https://github.com/onflow/developer-portal/issues/466

**Comment by 10thfloor** [comment]
We have these now! 
https://docs.google.com/spreadsheets/d/1YzKJEF8Mwknjhkz3zRrnTflCh6ZNjCRZOabcD3g_lCk/edit#gid=0
