### ISSUE TITLE
SRE

### ISSUE THREAD

**Issue by LaurenIke** [onflow/developer-portal#680]
## Overview:

Work will proceed in 2 phases: 
1) Protect [[fly.io](http://fly.io/)](http://fly.io) deployment using WAF and CDN

2) Migrate deployment to internal Kubernetes infrastructure

This line item accounts for only Phase 1

---

CDN Caching and WAF:

Caching (CDN) and Application Firewall implementation will go ahead.

 What to cache? Decide what to add to CDN cache.

Progress:

- List of endpoints to enable WAF access has been provided to SRE
- WAF implementation for staging is in progress
- Migrating SSL to Cloudflare is in progress

@Parin Maru To create issues for items of work (UPDATE: linked below)

---
(From @parindey02)
Tracking WAF enablement in Staging: https://github.com/dapperlabs/dapper-flow-hosting/issues/851
Caching on Cloudflare for Developer Portal: https://github.com/dapperlabs/dapper-flow-hosting/issues/852

**Comment by codingone21** [comment]
Updated linked issues from Parin, added to the description

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs with vercel deployments
