### ISSUE TITLE
Deployment strategy for preview and dead link check 

### ISSUE THREAD

**Issue by LaurenIke** [onflow/developer-portal#691]
## Feature Story 
As a Dapper team, we should discuss and agree upon a deployment strategy for the preview and dead links work. 

## Issue 
Currently, the work for preview and dead link checking is only deployed on staging.  It has been communicated that it would be preferred if this lived on a production instance as well. 

Considerations: 
- if main and production diverge in someway that effects the docs, unclear what would be show a preview of
- security: difference between running production environment vs. staging environment
- don't want to burden the production server with additional workload

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs with vercel previews
