### ISSUE TITLE
Getting double screen on Firefox 

### ISSUE THREAD

**Issue by ggpt-labs** [onflow/developer-portal#693]
**Screenshots**
<img width="1502" alt="Screen Shot 2022-09-30 at 8 02 23 PM" src="https://user-images.githubusercontent.com/110695966/193377147-28d7a774-2fd0-46ea-b519-c0de4b7d2e20.png">

**Desktop:**
 - OS: iOS
 - Browser: Firefox 
 - Version 105.0.1 (64-bit)

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs
