### ISSUE TITLE
Broken image link on Cadence - 08 Marketplace Compose 

### ISSUE THREAD

**Issue by LaurenIke** [onflow/developer-portal#699]
## Issue 
There is a broken image link on the Marketplace Compose screen that needs to be resolved. 

## Steps to reproduce 
- visit this link - https://developers.flow.com/cadence/tutorial/08-marketplace-compose
- scroll part way down the page
- notice under Marketplace Setup, there is a broken image link

**Comment by 10thfloor** [comment]
Closing, as not related to site source code.|
Created issue for Cadence devs here: https://github.com/onflow/cadence/issues/2032
