### ISSUE TITLE
Make images expandable 

### ISSUE THREAD

**Issue by LaurenIke** [onflow/developer-portal#701]
## Feature Story
As a user looking at images on the developer portal, I would like to expand them to see them at a larger scale. 

## Notes 
- Can we make images expandable - similar to the code block when you click on the [ ] symbol to make it large
- Content like this https://developers.flow.com/flow/core-contracts/nft-storefront makes it hard to see the image without open in new tab

**Comment by nialexsan** [comment]
https://github.com/onflow/docs/issues/256
