### ISSUE TITLE
Understand why cadence content update did not apply on production site

### ISSUE THREAD

**Issue by schpet** [onflow/developer-portal#703]
**Describe the bug**

cadence updated docs/language/interfaces.mdx in this commit:
https://github.com/onflow/cadence/commit/50aff9d961d197623c89250c3fb011f98661f380

expected:
page should have updated

observed:
page was serving stale content on production

todo:

- [ ] understand why this update didn't happen
- [ ] if it's a problem in the logic, find the webhook payload and write a test to confirm it invalidates the cache

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs
