### ISSUE TITLE
Support reading version information from a flow-docs json and reflect that in a dropdown form input 

### ISSUE THREAD

**Issue by LaurenIke** [onflow/developer-portal#705]
## Feature Story 

External repos will be able to opt into versioned docs by specifying a version in their flow-docs.json configuration file.

## Technical Implementation Notes 

Suggested schema:

```json
{
  "$schema": "https://developers.flow.com/schemas/flow-docs.json",
  "versions": [
    { "ref": "v0.26.0", "label": "0.26.0", "active": true },
    { "ref": "v0.25.0", "label": "0.25.0" }
  ]
}
```

Please note this differs from the schema in the PRD – this change supports labels, and also explicitly defines the source as "ref" to signal that this can be any ref that the github api understands given we are looking to support sourcing versions from both branches and tags[^1]. additionally, this will let us add more fields for future feature needs.

[^1]: we _may_ want to consider requiring that an explicit ref is provided, e.g. `tags/<tag name>` (or maybe `refs/tags/<tag name>` ?) in the case of tags, or `heads/<branch name>` in the case of branches – whatever is the most consistent with github's api for fetching content probably makes sense here as well. also consider caching: #708

Suggested validations:
- ensure exactly one version exists with `active: true` 
- ensure all labels are unique so they can be used in a dropdwon

[PRD](https://docs.google.com/document/d/1EGhTFvu4AVxLjOx1HMa28HhaKLehREH9ceYEUudxLEU/edit#)

**Estimated development time** 
TBD 

**Release date**
TBD

**Comment by LaurenIke** [comment]
Next Action: 
@schpet to fill in some additional details for this ticket

**Comment by schpet** [comment]
@codingone21 this is ready for review
