### ISSUE TITLE
Load documents from the branch (or tag) matching the version selection chosen

### ISSUE THREAD

**Issue by LaurenIke** [onflow/developer-portal#706]
## Feature Story 

As a document viewer, when I choose a specific version of the docs that version of the docs should be shown. 

## Technical Implementation Notes 

- links within the documents should keep me on the version I am looking at
- sidebar content should be specific to that version
- the "versions" state from the flow-docs.json file should always come from the default branch for that repo / doc-collection
- a URL search parameter should be added to indicate the version in the URL, e.g. `/cadence/FAQ?version=0.26.0`

 

[PRD](https://docs.google.com/document/d/1EGhTFvu4AVxLjOx1HMa28HhaKLehREH9ceYEUudxLEU/edit#)

**Estimated development time** 
TBD 

**Release date**
TBD

**Comment by LaurenIke** [comment]
Next Action: 
@schpet to fill in some additional details for this ticket

**Comment by schpet** [comment]
@codingone21 this is ready for review

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs from one source of truth with preview links from vercel
