### ISSUE TITLE
Indicate when you are viewing a version of the docs that are not the default

### ISSUE THREAD

**Issue by LaurenIke** [onflow/developer-portal#707]
## Feature Story 

As a person viewing a version of the docs that is not the "active" version, I see a message at the top of the page indicating that

## Technical Implementation Notes 
- re-use the UI shown on previews
- needs copy

[PRD](https://docs.google.com/document/d/1EGhTFvu4AVxLjOx1HMa28HhaKLehREH9ceYEUudxLEU/edit#)

**Estimated development time** 
TBD 

**Release date**
TBD

**Comment by LaurenIke** [comment]
Next action:
@schpet to fill in some additional details for this ticket

**Comment by schpet** [comment]
@codingone21 this is ready for review

**Comment by nialexsan** [comment]
switched to static builds with versioning from docusaurus:
https://github.com/onflow/docs
