### ISSUE TITLE
Cache a version of the document for the viewer and invalidate this cache when documents are changed in remote repos

### ISSUE THREAD

**Issue by LaurenIke** [onflow/developer-portal#708]
## Feature Story 

As a user when I view a versioned document, I get a fast cached response unless I'm the first person to visit that document

As a content author, when I push changes to the documentation, those changes are reflected immediately on the docs site 

## Technical Implementation Notes 

[PRD](https://docs.google.com/document/d/1EGhTFvu4AVxLjOx1HMa28HhaKLehREH9ceYEUudxLEU/edit#)

**Estimated development time** 
TBD 

**Release date**
TBD

**Comment by LaurenIke** [comment]
Next action: 
@schpet to fill in some additional details for this ticket

**Comment by schpet** [comment]
@codingone21 this is ready for review

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs from one source of truth
