### ISSUE TITLE
Exclude inactive document versions from Algolia search index 

### ISSUE THREAD

**Issue by LaurenIke** [onflow/developer-portal#709]
## Feature Story 

As a person viewing other pages, when I make a search query, I only get search results from the active version of documents to prevent duplicate search results

As a person viewing a versioned document, when I make a search query I do not see results for versions except the version I am currently looking at

## Technical Implementation Notes 
- need to explore and understand what is possible with algolia 
- keep in mind algolia only crawls periodically, and not every time a push event is processed, so results might be delayed

[PRD](https://docs.google.com/document/d/1EGhTFvu4AVxLjOx1HMa28HhaKLehREH9ceYEUudxLEU/edit#)

**Estimated development time** 
TBD 

**Release date**
TBD

**Comment by LaurenIke** [comment]
Next Action: 
@schpet to fill in some additional details for this ticket

**Comment by schpet** [comment]
@codingone21 this is ready for review

**Comment by nialexsan** [comment]
switched to typesense:
https://github.com/onflow/docs
