### ISSUE TITLE
Adding back Playground Links

### ISSUE THREAD

**Issue by a5chanda** [onflow/developer-portal#719]
**Add Playground links to the following components:**
- Documentation/Learn tab
- Cadence/Cadence Resources
- [Cadence / 01 First Steps](https://developers.flow.com/cadence/tutorial/01-first-steps) - Would be good to have a link to the Playground at the top. Should mention that the tutorial will be briefly explaining what the Playground is and have an icon linking to it
- Adding a specific card that will directly take the user to the playground on this page <img width="1035" alt="image" src="https://user-images.githubusercontent.com/31371847/196521114-6a0c0909-7448-4f97-a96e-b1276e3acd97.png">
- [Getting Started Page](https://developers.flow.com/getting-started) should have Playground as one of the top links for the Try section <img width="1016" alt="image" src="https://user-images.githubusercontent.com/31371847/196522767-52717f7b-1a57-4fe4-988a-99f7b7d6b218.png">

**Assets Required**

For [Hello World tutorial](https://developers.flow.com/cadence/tutorial/02-hello-world) it would be nice to have a clickable icon for the playground where the link to the playground tutorial is. Same thing for:

- [Resource Contract Tutorial](https://developers.flow.com/cadence/tutorial/03-resources) 
- [Capabilities Tutorial](https://developers.flow.com/cadence/tutorial/04-capabilities)
- [NFT Tutorial Pt 1](https://developers.flow.com/cadence/tutorial/05-non-fungible-tokens-1)
- [NFT Tutorial Pt 2](https://developers.flow.com/cadence/tutorial/05-non-fungible-tokens-2)
- All the remaining tutorials

**Comment by 10thfloor** [comment]
@srinjoyc Could you coordinate getting new playground image assets from design resource?

**Comment by 10thfloor** [comment]
@a5chanda Link to Playground on the Cadence homepage needs PR to Cadence repo: 
-> https://github.com/onflow/cadence/pull/2078

**Comment by 10thfloor** [comment]
PR in progress here: 
https://github.com/onflow/developer-portal/pull/720

**Comment by srinjoyc** [comment]
@10thfloor we don't have design resources atm - could we use an existing asset?

**Comment by 10thfloor** [comment]
@srinjoyc 
Yup, I used an existing asset: https://github.com/onflow/developer-portal/pull/720

**Comment by 10thfloor** [comment]
@srinjoyc @a5chanda 
You'll need to visit the portal using the preview links generated here: 
https://github.com/onflow/cadence/pull/2078

TO make this work we need to merge both of these PRs at the same time.

**Comment by a5chanda** [comment]
@10thfloor can we add the playground links to the nav as well? In particular the following tabs:
- Documentation/Learn tab
- Cadence/Cadence Resources

**Comment by 10thfloor** [comment]
Done here 1067adfa

**Comment by 10thfloor** [comment]
Everything is merged on the Cadence side as well.
