### ISSUE TITLE
Portal Alerts

### ISSUE THREAD

**Issue by srinjoyc** [onflow/developer-portal#736]
The following alerts should be sent to #flow-developer-portal-alerts: 

On a staging deployment:
- Triggered when any externally connected repositories **submits** a PR to their `docs` folder such as the `onflow/fcl-js` and `onflow/cadence`. 
- This seems to work fine but should add the following info in the alert - repository, author, and if possible (optional) the link to the PR.

On a production deployment:
- Triggered when any externally connected repositories **merges** a PR to their `docs` folder such as the `onflow/fcl-js` and `onflow/cadence`. 
- This currently is not showing up on slack at all. It should include the same properties as above.

If there are any errors in the CI/CD process on either production or staging, they should be reported on slack as well.

Nice to have (optional):
- Report # broken links from Agolia on this slack channel

**Comment by nialexsan** [comment]
static builds from single source of truth
https://github.com/onflow/docs/
