### ISSUE TITLE
Figure out the intended link for https://developers.flow.com/concepts/transaction-lifecycle

### ISSUE THREAD

**Issue by huyndo** [onflow/developer-portal#761]
In https://developers.flow.com/nodes/access-api#block, there's a link pointing to "block formation guide" that's broken. This might be referring to the white paper in https://flow.com/technical-paper but this needs to be confirmed.

**Comment by gpavlov2016** [comment]
The original link was created by @psiemens, reaching out on slack to figure out the correct replacement

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs
