### ISSUE TITLE
Reliability: Update content checker relative link checker

### ISSUE THREAD

**Issue by bthaile** [onflow/developer-portal#766]
The guiding principle of content checker, links in markdown should resolve correctly in github. 

Secondary the developer portal will interpret the links so they work in developer portal. We want to get away from making doc updates to fix links in dev portal only and break the natural linking in github.

 - [x] content checker should understand the repos docs root folder, it's in flow-docs.json and in dev portal docCollections files
 - [x] add checking against fully qualified links in the updated docs. 

Fix Hinting 
 - [ ] currently some relative links are marked as invalid and are not
 - [ ] provide more suggestions rather than just one give 2-3

Future Support
 - [x] allow authors to use `../` in relative links

**Comment by gpavlov2016** [comment]
What does it mean that the link should work in github?
Why is there a distinction between a link working in github and on the dev portal, shouldn't it work in both of them?

**Comment by bthaile** [comment]
Issue with low confidence in content checker is the scope is too large. In order to address confidence and stability the scope needs to be narrowed. "work in github" means the links in the markdown should be navigable from within github. The dev portal should massage the markdown to fit it's own needs. 
There should not be broken links in the markdown as it exists within in github.

**Comment by bthaile** [comment]
closing, content checker has been updated and we'll create specific ticket as needed.
