### ISSUE TITLE
Dev task, dev iteration cycle for content checker

### ISSUE THREAD

**Issue by bthaile** [onflow/developer-portal#767]
Currently it is possible to spin up the content checker locally using docker. 

It would be beneficial to test existing PRs against a local version of the github app webhook. The proposed dev iteration cycle:
1. spin up docker
2. write a test harness to massage if needed and send a payload to webhook
3. make sure output is seen for debugging
4. bonus would be to allow vscode to attach to the webhook process in order to step through the code as it executes

**Comment by huyndo** [comment]
Preliminary test harness is done per #798

**Comment by bthaile** [comment]
test harness has been documented here.
https://github.com/onflow/developer-portal/tree/production/app/cms/doc-validation/test

We can create new issues to extend and modify.
