### ISSUE TITLE
Add WebVitals for Dev Portal

### ISSUE THREAD

**Issue by gpavlov2016** [onflow/developer-portal#768]

**Comment by gpavlov2016** [comment]
Webvitals enable page load speed measurements on the client and stream to GA

**Comment by 10thfloor** [comment]
@bthaile look here: 
https://github.com/onflow/developer-portal/blob/production/app/entry.client.tsx

**Comment by bthaile** [comment]
As Mac has already identified.

Looks like PerformanceNavigationTiming is logged using onTTFB.  "Time To First Byte" events are logged.  
https://github.com/onflow/developer-portal/blob/4afdd73d127cdfc4893b19a207645a1f3ca6c976/app/entry.client.tsx#L21

I will update to use the newest web-vitals lib version

**Comment by bthaile** [comment]
Merged web-vitals lib upgraded to "main" branch, so possible to verify on staging if all events are coming through.

**Comment by fotescodev** [comment]
- [ ] @fotescodev to verify with Nikita to confirm it works

**Comment by nialexsan** [comment]
no need for web vitals with static builds
https://github.com/onflow/docs
