### ISSUE TITLE
Fix https://flow-docs-staging.fly.dev/mobile page

### ISSUE THREAD

**Issue by gpavlov2016** [onflow/developer-portal#784]
The page should present content from repository: ([mobile-docs](https://github.com/onflow/mobile-docs]))[https://github.com/onflow/mobile-docs] repo
Currently it shows preview not found
url not working
https://flow-docs-staging.fly.dev/mobile

![Image](https://user-images.githubusercontent.com/16441017/206764970-cf0f8fb0-d921-4841-a2c0-00b56ffbcddd.png)

**Comment by bthaile** [comment]
reopening issue, redirect to index.md didn't work

**Comment by bthaile** [comment]
Verified this issue has been fixed
