### ISSUE TITLE
Remove kitty items

### ISSUE THREAD

**Issue by bthaile** [onflow/developer-portal#803]
Need to remove kitty items from developer portal
 - identify all places kitty-items shows up in developer portal
   - search onflow repo docs to remove references.
 - remove configuration that loads kitty items in dev portal. 
  - look in doc-collections in dev portal repo

as reference, here is the url
https://developers.flow.com/learn/kitty-items

**Comment by nialexsan** [comment]
https://github.com/onflow/docs/issues/254
