### ISSUE TITLE
Network Status Dead Link

### ISSUE THREAD

**Issue by bthaile** [onflow/developer-portal#805]
https://developers.flow.com/network/

Each network status component points to a dead link. What should they point to?
 - Question is answered below

TODO:
Based on comment below, looks like there are spaces instead of `-` in the links. 

Example
broken: https://developers.flow.com/network/flow-mainnet%20core%20components
should be: https://developers.flow.com/network/flow-mainnet-core-components

Other good links
https://developers.flow.com/network/flow-mainnet-access-apis
https://developers.flow.com/network/flow-sandboxnet-core-components
https://developers.flow.com/network/flow-sandboxnet-access-apis

**Comment by vishalchangrani** [comment]
The link should point to a page such as this one for testnet - https://developers.flow.com/network/flow-testnet.

The page needs to pull data from the status page - https://status.onflow.org/ and date for the next spork from the page https://developers.flow.com/nodes/node-operation/upcoming-sporks.

**Comment by bthaile** [comment]
this is fixed with merged PR
