### ISSUE TITLE
Update the Section Thumbnail to a new design referring to Mobile

### ISSUE THREAD

**Issue by fotescodev** [onflow/developer-portal#834]
Update the Flow Mobile section logo, and other icons to the new design below: 

https://www.figma.com/file/Ug5QlSD3uPxg5MHFwbApVe/Flow-Dev-Portal?node-id=116%3A44384

![Image](https://user-images.githubusercontent.com/44682521/215180482-dfb6af9f-aaea-41f1-92ad-4397b4e0a0f4.png)
![Image](https://user-images.githubusercontent.com/44682521/215180480-1a76de22-4e3c-4ebe-b4d8-cc564fdc393f.png)
![Image](https://user-images.githubusercontent.com/44682521/215180481-3240f4f4-27bb-4e7d-830f-8dc05e990c13.png)

**Comment by MrDSGC** [comment]
done
