### ISSUE TITLE
Create a Mobile section under `documentation` drop down

### ISSUE THREAD

**Issue by fotescodev** [onflow/developer-portal#838]
Create a `mobile` section under the `documentation` drop down menu:

<img width="1613" alt="Screen Shot 2023-01-25 at 10 21 35 AM" src="https://user-images.githubusercontent.com/44682521/214602789-eed81b5e-6029-4317-a39f-c7760afeefb5.png">

**Comment by bthaile** [comment]
We need data to fill in the new "mobile" section under documentation. If we want to keep the same structure:
1. image with text 
2. Two Column 
 - headers 
  - with links for each column.
  - footer links

**Comment by fotescodev** [comment]
- [ ] @fotescodev to provide info above
