### ISSUE TITLE
Add Mobile section under `Learn` dropdown

### ISSUE THREAD

**Issue by fotescodev** [onflow/developer-portal#841]
Currently the mobile section points to `Find A Guide` - create a separate Mobile Section and place it under the `Learn Subsection`, for example where Kitty Items is residing currently: 
<img width="1127" alt="Screen Shot 2023-01-25 at 10 36 26 AM" src="https://user-images.githubusercontent.com/44682521/214607312-19197309-4537-49c6-8ebd-ca740a8ed1de.png">
<img width="645" alt="Screen Shot 2023-01-25 at 10 31 12 AM" src="https://user-images.githubusercontent.com/44682521/214607360-5c7cb4b3-f891-49e8-9d95-893838a83f63.png">

**Comment by MrDSGC** [comment]
done
