### ISSUE TITLE
Add Form to issue templates

### ISSUE THREAD

**Issue by bthaile** [onflow/developer-portal#846]
Issue Form Template.

Reference:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

Get better information user submits and issue by using Forms, dropdowns, ...

**Comment by nialexsan** [comment]
https://github.com/onflow/docs/issues/259
