### ISSUE TITLE
handle request Sentry issue reported 

### ISSUE THREAD

**Issue by bthaile** [onflow/developer-portal#861]
![image](https://user-images.githubusercontent.com/3970376/215527327-4e83bc4d-24a6-456e-b326-208cc77d9b46.png)

Issue has to do with spam POST request. IT to add a service between dns and fly.io to filter out POST requests to main site. 

Note: staging does need to allow POST request for content checker github action.

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs
