### ISSUE TITLE
Blank pages.

### ISSUE THREAD

**Issue by 10thfloor** [onflow/developer-portal#870]
# Missing content?
There is no content on: https://developers.flow.com/mobile/get-started
The other pages in this section are basically empty as well. 

![image](https://user-images.githubusercontent.com/901466/215825116-deda4a89-cc4f-4bd8-8d3d-069fff515a77.png)

**Comment by MrDSGC** [comment]
Thanks for the heads up Mack :)

**Comment by MrDSGC** [comment]
https://github.com/onflow/mobile-docs/pull/8

**Comment by bthaile** [comment]
closing
