### ISSUE TITLE
Create three new sections on the main page `Learn Flow` `Flow Quickstarts` `Documentation`

### ISSUE THREAD

**Issue by fotescodev** [onflow/developer-portal#877]
Replace the existing main section of the homepage with the following: 

<img width="749" alt="Screen Shot 2023-02-01 at 11 36 00 AM" src="https://user-images.githubusercontent.com/44682521/216104982-e4c2ccdb-59f5-4ac2-8fc9-4559f1decfea.png">

Design: https://www.figma.com/file/Ug5QlSD3uPxg5MHFwbApVe/Flow-Dev-Portal?node-id=194%3A35472

**Comment by MrDSGC** [comment]
complete
