### ISSUE TITLE
Provide a way to preview in-progress documents

### ISSUE THREAD

**Issue by 10thfloor** [onflow/developer-portal#90]
A universal request from docs authors has been: 
Let me preview my edits in the site before deploying them.

We need to investigate how to do this using Fly.io and Remix.

**Comment by gpavlov2016** [comment]
One potential solution is to define a branch on every upstream repo that will be staging bound for docs and the result can be view on the staging site

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs with preview links from vercel
