### ISSUE TITLE
Community page's FLIP information source is wrong

### ISSUE THREAD

**Issue by justinbarry** [onflow/developer-portal#929]
On [community page](https://developers.flow.com/community) the FLIPs listing isn't correct showing only one active flip.
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/328965/219230397-d36f7d58-f069-481a-baf6-2dd574623f6e.png">

**Comment by bthaile** [comment]
need to determine if this component will be rebuilt in new dev portal, tracking effort on a different ticket. closing
