### ISSUE TITLE
Network window extends when networks are loaded

### ISSUE THREAD

**Issue by sideninja** [onflow/developer-portal#939]
As seen in pictures the network tab window extends a lot when networks are loaded. I think it should probably be changed to not do that. I think it would be better to not contain so much information in navigational elements. I think we should move this to a separate page and the navigation element can only hold summary, so if all things are green it will contain green icon saying everything is fine, if one is red then it contain the one that's not ok and an orange icon and see more for details button that takes you to the mentioned page. 

How it currently expands 
![Screenshot 2023-02-20 at 18 15 34](https://user-images.githubusercontent.com/75445744/220168293-b4bc530c-be0c-434f-ba5d-c219c975698b.png)

![Screenshot 2023-02-20 at 18 15 29](https://user-images.githubusercontent.com/75445744/220168299-8c03ac2b-e5a9-49bb-b575-17613deed25c.png)

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs with a link to network status
